language: objective-c
before_install:
- chmod +x scripts/add-key.sh
- chmod +x scripts/remove-key.sh
- chmod +x scripts/update-bundle.sh
- chmod +x scripts/sign-and-upload.sh
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/AppNavigation_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/AppNavigation_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild test -workspace MultiSchemeTravisNavigation.xcworkspace -scheme QA-MultiSchemeTravisNavigation
  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace MultiSchemeTravisNavigation.xcworkspace -scheme QA-MultiSchemeTravisNavigation
  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace MultiSchemeTravisNavigation.xcworkspace -scheme QA-MultiSchemeTravisNavigation
  -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="AppNavigation"
  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
  - PROFILE_NAME="AppNavigation_Ad_Hoc"
  - secure: vEHjvdPATlFJQbu7paItB5CWOpC6m+svDAGweOTu1KtUTI6gTzuJc836TZcL/bk7u4NsR5s+yPCaGlVW+tl+guSAXE4hU0rjatR9y536S6y6YoDwFdrK/yUbCi1ppI9LtflFqNvQHWmBtXeDLFZ63jFCEGlQqKquvp/D3+9DIwg=
  - secure: hHI+NkEBaZflriIZEqHiZoS7LT8tbPPU7wVH8dgI7+kIzxbCWU6uK9VWebB4OqUGcpdVd+yTROIxuOGMLFGM52QoW18pNBUs9JwalRybOFAFu7WgQ8H2bknH0ixThm0qdr0aE0DyW5o9aN+zhv/sdmrOW+zEsqjI67PUjQyph8w=
